# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70256f6c8a094e70a7099e24ef13dbcb0f34ac314098e9598db2b3c1506dc412f0989e5df9cd2567e9b4c96fade5f9caf609436d69cd1f89b1f7cd20a2333b6f

test:
  secret_key_base: 336ef2296139869004f818a03845848884c3b12f775be86d8e902ad205835172eeef35a7dbde100612dfd4a8b73c92dbd882d6834a59341df96030ee3a8bf056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
